// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs3LH_Md85IHwYoXc6wOyew2C_X812wwU',
    appId: '1:410356135842:web:86691ba7bb715afa3464fb',
    messagingSenderId: '410356135842',
    projectId: 'nashmi-rescue',
    authDomain: 'nashmi-rescue.firebaseapp.com',
    databaseURL: 'https://nashmi-rescue-default-rtdb.firebaseio.com',
    storageBucket: 'nashmi-rescue.firebasestorage.app',
    measurementId: 'G-SWM14FXNJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6wEiGVjxXrRCOqxeSbNdySl1-LT2Wyho',
    appId: '1:410356135842:android:4dd3bb7a6e7d3cb03464fb',
    messagingSenderId: '410356135842',
    projectId: 'nashmi-rescue',
    databaseURL: 'https://nashmi-rescue-default-rtdb.firebaseio.com',
    storageBucket: 'nashmi-rescue.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK9OtM2u_LaasQBt3-mQi1XKxRfsW_GtY',
    appId: '1:410356135842:ios:cd1d3c78c7b4d9593464fb',
    messagingSenderId: '410356135842',
    projectId: 'nashmi-rescue',
    databaseURL: 'https://nashmi-rescue-default-rtdb.firebaseio.com',
    storageBucket: 'nashmi-rescue.firebasestorage.app',
    iosBundleId: 'com.example.nashmi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK9OtM2u_LaasQBt3-mQi1XKxRfsW_GtY',
    appId: '1:410356135842:ios:cd1d3c78c7b4d9593464fb',
    messagingSenderId: '410356135842',
    projectId: 'nashmi-rescue',
    databaseURL: 'https://nashmi-rescue-default-rtdb.firebaseio.com',
    storageBucket: 'nashmi-rescue.firebasestorage.app',
    iosBundleId: 'com.example.nashmi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs3LH_Md85IHwYoXc6wOyew2C_X812wwU',
    appId: '1:410356135842:web:7a638b341767b78f3464fb',
    messagingSenderId: '410356135842',
    projectId: 'nashmi-rescue',
    authDomain: 'nashmi-rescue.firebaseapp.com',
    databaseURL: 'https://nashmi-rescue-default-rtdb.firebaseio.com',
    storageBucket: 'nashmi-rescue.firebasestorage.app',
    measurementId: 'G-VLMD1QK7T5',
  );
}
